baseURL = "/"
languageCode = "en-us"
title = "Working At Home Choice"
theme = "ananke"
CanonifyURLs = true
sectionPagesMenu = "main"
DefaultContentLanguage = "en"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = "https://i.ibb.co/p1wLfx5/work-at-home-choice-green-and-white-text-removebg-preview.png"
  description = ""
  facebook = ""
  twitter = ""
  instagram = "#"
  youtube = "#"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "https://images.unsplash.com/photo-1551275073-f8adef647c1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1347&q=80"
  recent_posts_number = 2
